apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels: # <- ⚠️ To link the deployment to the pods
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: # <- ⚠️ To link the pod(s) to the deployment or service(s)
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 8080