apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # <- ⚠️ To link the service to the pod(s)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080